### ISSUE TITLE
Custom CSS/JS is unusable in Windows

### ISSUE THREAD

**Issue by starsriver** [egoist/devdocs-app#25] opened 2017-06-13 13:05 UTC
I downloaded DevDocs.Setup.0.3.0-ia32.exe from release.

I installed in Windows 10 15063, but cannot find Custom CSS/JS like this
![default](https://user-images.githubusercontent.com/11370806/27083662-d9e5a702-507b-11e7-949d-0ef1c193fc06.PNG)

**Comment by Positive07** [comment] 2017-06-13 14:22
Yes, there is no menu in Windows systems. Able to replicate in Windows 10 x64 running latest

**Comment by starsriver** [comment] 2017-06-13 15:08
@Positive07 Thanks for your reply.

**Comment by Positive07** [comment] 2017-06-13 15:20
Closed accidentaly @starsriver? The issue is relevant and should be fixed

**Comment by egoist** [comment] 2017-06-13 16:21
<img width="353" alt="2017-06-14 12 18 59" src="https://user-images.githubusercontent.com/8784712/27092828-4f433ec2-5097-11e7-9734-8791bd6f7f76.png">

Hmm, weird that I can see the menu, maybe something went wrong in the packaged version

**Comment by Positive07** [comment] 2017-06-13 18:30
Oh this issue is pretty dumb! The 0.3.0 release has `autoHideMenu: true` in the window configuration so you need to press `Alt` to see the menu.

Note that master doesn't have `autoHideMenu: true` by default anymore, which is better!

**Comment by egoist** [comment] 2017-06-13 18:43
@Positive07 thanks for telling me that 👍🏻

[v0.4.0](https://github.com/egoist/devdocs-app/releases/tag/v0.4.0) should fix this.

**Closed by egoist** 2017-06-13 18:43 UTC

**Comment by starsriver** [comment] 2017-06-14 04:49
@Positive07  this not a bug really😂, thank you👍🏻
